import{a as l,S as u,i as d}from"./assets/vendor-d7a5248b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();l.defaults.headers.common["x-api-key"]="live_Udzu26achjGYA2BMtCNuKo0suxVLZlHl4HcY5ttBEPXlVv2LnACvWjDJ7ZrZnYT2";async function f(){return await l.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function m(e){return await l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(r=>r.data)}const a={breedSelect:document.querySelector(".js-breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),title:document.querySelector(".animate__animated")};function s(e,r){e.classList.toggle("hidden",!r)}y();s(a.breedSelect,!1);s(a.loader,!0);const p=new u({select:a.breedSelect});async function h(){try{s(a.loader,!0),s(a.catInfo,!1);const e=a.breedSelect.value,r=await m(e);g(r)}catch{d.show({position:"center",message:"An error have ocurred. Please reload the page"})}s(a.loader,!1)}function g(e){const r=e[0].url,n=e[0].breeds[0],c=`<div class="card">
  <img class="img" src="${r}" alt="${n.name}"/>
      <div class="info">
        <h2 class="name">${n.name}</h2>
        <p><span class="description">Description: </span> ${n.description}</p>
        <p><span class="temperament">Temperament: </span> ${n.temperament}</p>   
       </div>
</div>`;a.catInfo.innerHTML=c,s(a.catInfo,!0)}async function y(){try{await f().then(e=>{const r=e.map(({id:n,name:c})=>({value:n,text:c}));console.log(r),p.setData(Array.from(r))}),s(a.breedSelect,!0),a.breedSelect.addEventListener("change",h)}catch(e){console.log(e),d.show({position:"center",message:"Oops! Something went wrong! Try reloading the page!"})}s(a.loader,!1)}
//# sourceMappingURL=commonHelpers.js.map
